project_id = "tvqwujlpgqoofmmvzxzw"

[functions.google-analytics-auth]
verify_jwt = true


[functions.openai-chat]
verify_jwt = true

[functions.google-analytics-data]
verify_jwt = true

[functions.manage-api-keys]
verify_jwt = true

[functions.use-api-key]
verify_jwt = true

[functions.oauth-auth]
verify_jwt = true

[functions.oauth-callback]
verify_jwt = false