// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvqwujlpgqoofmmvzxzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2cXd1amxwZ3Fvb2ZtbXZ6eHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzQ4ODUsImV4cCI6MjA2NzAxMDg4NX0.sSx7Jc2BoJsLnizkzWHsjs6eE_b4vTAVuAp4O0if_Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});